networks:
  kafka-net:

services:
  kafka:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: "GexnRXXwT32pPP-0JhOBjg"
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # ====== LISTENERS ======
      KAFKA_LISTENERS: >
        INTERNAL://0.0.0.0:29092,
        EXTERNAL://0.0.0.0:9092,
        CONTROLLER://0.0.0.0:9093
      # advertised:
      # EXTERNAL must IP
      KAFKA_ADVERTISED_LISTENERS: >
        INTERNAL://kafka:29092,
        EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        INTERNAL:PLAINTEXT,
        EXTERNAL:PLAINTEXT,
        CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # ====== LOGGING & Data  ======
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: >
        kafka=INFO,
        kafka.controller=INFO,
        kafka.log.LogCleaner=INFO,
        state.change.logger=INFO,
        kafka.producer.async.DefaultEventHandler=INFO
      KAFKA_LOG4J_TOOLS_LOGLEVEL: ERROR
      
      # ====== SINGLE NODE REPLICATION ======
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      # SIZE LIMIT
      #KAFKA_MESSAGE_MAX_BYTES: 5000000
      #KAFKA_REPLICA_FETCH_MAX_BYTES: 5000000
      #KAFKA_FETCH_MESSAGE_MAX_BYTES: 5000000
    volumes:
      - ./data:/var/lib/kafka/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    healthcheck:
      test:
        [
          "CMD",
          "kafka-broker-api-versions",
          "--bootstrap-server",
          "localhost:9092",
        ]
      interval: 8s
      timeout: 5s
      retries: 8
      start_period: 40s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - kafka-net
    ports:
      - "7200:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: k-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

      # ================= LOGGING =================
      LOGGING_LEVEL_ROOT: WARN
      LOGGING_LEVEL_COM_PROVECTUS: WARN
      LOGGING_LEVEL_COM_PROVECTUS_KAFKA_UI: WARN
    depends_on:
      kafka:
        condition: service_healthy
